:concurrency: 3
:timeout: 60
:verbose: true
:queues:
  - critical
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge

:scheduler:
  :schedule:
    cleanup_abandoned_carts_job:
      cron: '0 2 * * *' # Run every day 2:00 AM
      class: CleanupAbandonedCartsJob
      queue: default
      description: 'Marks inactive carts as abadoned and removes old abanoned cats'